const ts = require('typescript'), fs = require('node:fs'), path = require('node:path'), vm = require('node:vm'), assert = require('node:assert/strict');
const modules = new Map();
function load(file) {
  file = path.resolve(file);
  if (modules.has(file)) return modules.get(file);
  const exports = {};
  modules.set(file, exports);
  vm.runInNewContext(ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, { exports, require: name => load(path.resolve(path.dirname(file), name + '.ts')) });
  return exports;
}
const { updateCamera } = load('src/lib/camera.ts');
const { cameraGroups } = load('src/lib/display.ts');
const { createDefaultLander, MAP_WIDTH } = load('src/lib/simulation.ts');
let state = { custom: null, followPilotId: null };
state = updateCamera(state, { action: 'pan', dx: 1, dy: 1 }, []);
assert.ok(state.custom.x > MAP_WIDTH / 2);
assert.ok(state.custom.y > 600);
state = updateCamera(state, { action: 'zoom', factor: 1.25 }, []);
assert.equal(state.custom.zoom, 1.25);
const custom = JSON.stringify(state.custom);
state = updateCamera(state, { action: 'follow', pilotId: 'pilot' }, ['pilot']);
assert.equal(state.followPilotId, 'pilot');
assert.equal(JSON.stringify(state.custom), custom);
const followed = { id: 'pilot', lander: createDefaultLander() };
const other = { id: 'other', lander: { ...createDefaultLander(), x: 900, y: 120, a: 1 } };
const terrain = [[0, 100, MAP_WIDTH, 100]];
const groups = cameraGroups([other], followed, terrain, 1280, 720);
assert.equal(groups.length, 1);
assert.equal(groups[0][0].id, 'pilot', 'Follow overrides another landing');
assert.equal(cameraGroups([], followed, terrain, 1280, 720)[0][0].id, 'pilot', 'Follow persists outside approaches');
const landing = cameraGroups([other], undefined, terrain, 1280, 720);
assert.equal(landing[0][0].id, 'other');
assert.equal(cameraGroups([], undefined, terrain, 1280, 720).length, 0, 'After close-ups, use the idle viewport');
state = updateCamera(state, { action: 'unfollow' }, []);
assert.equal(JSON.stringify(state.custom), custom, 'Saved viewport survives temporary follow/landing views');
const before = state;
assert.equal(updateCamera(state, { action: 'zoom', factor: NaN }, []), before);
assert.equal(updateCamera(state, { action: 'follow', pilotId: 'missing' }, []), before);
for (let i = 0; i < 100; i++) state = updateCamera(state, { action: 'zoom', factor: 2 }, []);
assert.equal(state.custom.zoom, 12);
for (let i = 0; i < 100; i++) state = updateCamera(state, { action: 'zoom', factor: .5 }, []);
assert.equal(state.custom.zoom, .5);
state = updateCamera(state, { action: 'pan', dx: 1e9, dy: 1e9 }, []);
assert.ok(state.custom.x >= 0 && state.custom.x < MAP_WIDTH);
assert.ok(state.custom.y <= 5000);
assert.equal(updateCamera(state, { action: 'reset' }, []).custom, null);
console.log('Camera checks passed: pan, zoom limits, invalid commands, follow priority, landing close-ups, saved viewport, reset.');
