const ts = require('typescript'), fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict');
const exported = {};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/display-options.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, { exports: exported });
const { defaultDisplayOptions, validateDisplayOptions, rankPilots, leaderboardValue } = exported;
const base = defaultDisplayOptions();
assert.equal(base.leaderboardStat, 'landed');
const a = { id: 'a', name: 'Alpha', landed: 3, crashed: 1, bestStreak: 2, streak: 1, fastestMs: 11000, playedMs: 10000, activeSince: 1000, connections: 1 };
const b = { id: 'b', name: 'Beta', landed: 1, crashed: 4, bestStreak: 3, streak: 2, fastestMs: 9000, playedMs: 15000, activeSince: 0, connections: 0 };
const c = { ...a, id: 'c', name: 'Gamma', fastestMs: null };
assert.equal(rankPilots([a, b], 'landed', 10000)[0].id, 'a');
assert.equal(rankPilots([a, b], 'crashed', 10000)[0].id, 'b');
assert.equal(rankPilots([a, b], 'playedMs', 10000)[0].id, 'a');
assert.equal(rankPilots([a, b], 'bestStreak', 10000)[0].id, 'b');
assert.equal(rankPilots([a, b], 'streak', 10000)[0].id, 'b');
assert.equal(rankPilots([a, b, c], 'fastestMs', 10000)[0].id, 'b');
assert.equal(rankPilots([a, b, c], 'fastestMs', 10000).length, 2);
assert.equal(leaderboardValue(a, 'playedMs', 10000), 19000);
assert.equal(rankPilots([c, a], 'landed', 10000)[0].id, 'a');
const changed = validateDisplayOptions(base, { leaderboardStat: 'invalid', showQr: 'yes', showLeaderboard: false, qrTitle: '  SCAN   HERE  ' });
assert.equal(changed.leaderboardStat, 'landed');
assert.equal(changed.showQr, true);
assert.equal(changed.showLeaderboard, false);
assert.equal(changed.qrTitle, 'SCAN HERE');
assert.equal(base.showLeaderboard, true);
assert.equal(validateDisplayOptions(base, { leaderboardStat: '__proto__' }).leaderboardStat, 'landed');
console.log('Leaderboard checks passed: metric ordering, live time, unrecorded landings, ties, defaults, setting validation.');
