const ts = require('typescript');
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const optionsExports = {};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/display-options.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, { exports: optionsExports });
const exportsObject = {};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/lib/session-stats.ts', 'utf8'), {
  compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 },
}).outputText, { exports: exportsObject, structuredClone, require: () => optionsExports });
const { SessionTracker } = exportsObject;
const tracker = SessionTracker.create('session-1', 'Hack Night', 1000);
tracker.join('a', 'Pilot A', 2000);
tracker.join('b', 'Pilot B', 3000);
tracker.outcome('a', true, 12000);
tracker.outcome('a', true, 9000);
tracker.outcome('a', false, 0);
tracker.outcome('b', false, 0);
tracker.outcome('b', true, 15000);
let a = tracker.state.pilots.find(p => p.id === 'a');
assert.equal(tracker.state.joined, 2);
assert.equal(tracker.state.landed, 3);
assert.equal(tracker.state.crashed, 2);
assert.equal(a.bestStreak, 2);
assert.equal(a.streak, 0);
assert.equal(a.fastestMs, 9000);
tracker.leave('a', 22000);
assert.equal(a.playedMs, 20000);
tracker.join('a', 'Renamed Pilot', 30000);
tracker.join('a', 'Renamed Pilot', 31000);
tracker.leave('a', 32000);
assert.equal(a.connections, 1);
assert.equal(a.activeSince, 30000);
tracker.leave('a', 35000);
assert.equal(a.playedMs, 25000);
assert.equal(tracker.state.pilots.length, 2);
assert.equal(tracker.state.joined, 2);
assert.equal(a.name, 'Renamed Pilot');
const saved = tracker.snapshot(40000);
const restored = new SessionTracker(saved);
const b = restored.state.pilots.find(p => p.id === 'b');
assert.equal(b.connections, 0);
assert.equal(b.playedMs, 37000);
assert.equal(restored.state.landed, 3);
assert.equal(restored.state.pilots.find(p => p.id === 'a').bestStreak, 2);
const copy = restored.snapshot(46000);
copy.landed = 999;
assert.equal(restored.state.landed, 3);
console.log('Session stats checks passed: outcomes, fastest landing, streak reset, reconnect identity, overlapping connections, time played, persistence, snapshot isolation.');

assert.equal(tracker.state.name, 'Hack Night');
assert.equal(tracker.state.expiresAt, 1000 + 12 * 60 * 60 * 1000);
const nextSession = SessionTracker.create('session-2', 'Next Night', 50000);
nextSession.join('a', 'Pilot A', 51000);
assert.equal(nextSession.state.joined, 1);
assert.equal(nextSession.state.landed, 0);
assert.equal(nextSession.state.pilots[0].bestStreak, 0);
console.log('Named session and unique ship checks passed.');
